//// <auto-generated />
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using fincheckup.Data;

//namespace fincheckup.Migrations
//{
//    [DbContext(typeof(WsdContext))]
//    partial class WsdContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("fincheckup.Models.Accounts.AppUser", b =>
//                {
//                    b.Property<int>("UserID")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("DepartmentId");

//                    b.Property<string>("Description");

//                    b.Property<string>("Email");

//                    b.Property<string>("FirstName");

//                    b.Property<string>("LastName");

//                    b.Property<string>("Phone");

//                    b.Property<int>("ProjectRoleId");

//                    b.Property<string>("Title");

//                    b.HasKey("UserID");

//                    b.HasIndex("DepartmentId");

//                    b.HasIndex("ProjectRoleId");

//                    b.ToTable("AppUser","Account");
//                });

//            modelBuilder.Entity("fincheckup.Models.Definition.Status", b =>
//                {
//                    b.Property<int>("StatusId")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Color")
//                        .HasMaxLength(7);

//                    b.Property<string>("Description");

//                    b.Property<string>("Title")
//                        .HasMaxLength(100);

//                    b.HasKey("StatusId");

//                    b.ToTable("Status","Definition");
//                });

//            modelBuilder.Entity("fincheckup.Models.Definitions.Category", b =>
//                {
//                    b.Property<int>("CategoryId")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Description");

//                    b.Property<int>("ParentId");

//                    b.Property<int>("UserID");

//                    b.Property<string>("Title");

//                    b.HasKey("CategoryId");

//                    b.HasIndex("ParentId");

//                    b.HasIndex("UserID");

//                    b.ToTable("Category","Definition");
//                });

//            modelBuilder.Entity("fincheckup.Models.Organization.Department", b =>
//                {
//                    b.Property<int>("DepartmentId")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Description");

//                    b.Property<string>("Title");

//                    b.HasKey("DepartmentId");

//                    b.ToTable("Department","Organization");
//                });

//            modelBuilder.Entity("fincheckup.Models.Projects.ProjectRole", b =>
//                {
//                    b.Property<int>("ProjectRoleId")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Description");

//                    b.Property<bool>("Enabled");

//                    b.Property<string>("Title");

//                    b.HasKey("ProjectRoleId");

//                    b.ToTable("ProjectRole","Project");
//                });

//            modelBuilder.Entity("fincheckup.Models.Accounts.AppUser", b =>
//                {
//                    b.HasOne("fincheckup.Models.Organization.Department", "Department")
//                        .WithMany()
//                        .HasForeignKey("DepartmentId")
//                        .OnDelete(DeleteBehavior.Restrict);

//                    b.HasOne("fincheckup.Models.Projects.ProjectRole", "ProjectRole")
//                        .WithMany()
//                        .HasForeignKey("ProjectRoleId")
//                        .OnDelete(DeleteBehavior.Restrict);
//                });

//            modelBuilder.Entity("fincheckup.Models.Definitions.Category", b =>
//                {
//                    b.HasOne("fincheckup.Models.Definitions.Category", "Parent")
//                        .WithMany()
//                        .HasForeignKey("ParentId")
//                        .OnDelete(DeleteBehavior.Restrict);

//                    b.HasOne("fincheckup.Models.Accounts.AppUser", "AppUser")
//                        .WithMany()
//                        .HasForeignKey("UserID")
//                        .OnDelete(DeleteBehavior.Restrict);
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
